baseURL = 'https://callum.kerson.dev'
languageCode = 'en-gb'

theme = "lynx"
title = "Callum Kerson"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Callum Kerson"
  headline = "Some links to find me around the internet"
  image = "avatar.jpg"
  links = [
    { github = "https://github.com/callumkerredwards" },
    { twitter = "https://twitter.com/callumke" },
    { mastodon = "https://mastodonapp.uk/@callumke" },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
